/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo_Cliente.Cliente;
import Modelo_Cliente.ClienteExclusivo;
import Modelo_Cliente.ClienteNormal;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalTabbedPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class FormVista extends javax.swing.JFrame {

    /**
     * Creates new form FormVista
     */
    public FormVista() {
        initComponents();

        jTabbedPane1.setBackground(new Color(34, 86, 136));
        jTabbedPane1.setForeground(Color.WHITE);

        // Efecto de pestaña activa con color distinto
        jTabbedPane1.addChangeListener(e -> {
            int selectedIndex = jTabbedPane1.getSelectedIndex();
            for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                if (i == selectedIndex) {
                    jTabbedPane1.setBackgroundAt(i, new Color(20, 60, 100));
                } else {
                    jTabbedPane1.setBackgroundAt(i, new Color(34, 86, 136));
                }
            }
        });

        // 🖱️ Efecto hover al pasar el mouse
        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int hoverIndex = jTabbedPane1.indexAtLocation(e.getX(), e.getY());
                for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                    if (i == hoverIndex) {
                        jTabbedPane1.setBackgroundAt(i, new Color(106, 151, 193));
                    } else if (i != jTabbedPane1.getSelectedIndex()) {
                        jTabbedPane1.setBackgroundAt(i, new Color(34, 86, 136));
                    }
                }
            }
        });

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbNormal = new javax.swing.JRadioButton();
        rbExclusivo = new javax.swing.JRadioButton();
        btnCrearCliente = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUbicacionProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockProducto = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbbCliente = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductosDisponibles = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        btnAgregarPedido = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPedidoActual = new javax.swing.JTable();
        lblTotalPedido = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        btnConfirmarPedido = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResumenPedido = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rbBoleta = new javax.swing.JRadioButton();
        rbFactura = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        btnGenerarComprobante = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtComprobanteGenerado = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lblTotalPedidos = new javax.swing.JLabel();
        lblProductoMasVendido = new javax.swing.JLabel();
        lblTotalNormal = new javax.swing.JLabel();
        lblTotalExclusivo = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        lblAlertaActual = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtHistorialAlertas = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rbEfectivo = new javax.swing.JRadioButton();
        rbTarjeta = new javax.swing.JRadioButton();
        rbYape = new javax.swing.JRadioButton();
        lblResultadoPago = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtReciboPago = new javax.swing.JTextArea();
        btnRealizarPago = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        lblCodigoTarjeta = new javax.swing.JLabel();
        txtCodigoTarjeta = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 250, 251));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(34, 86, 136));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel8.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, -1));

        jLabel2.setText("Correo:");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel8.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 230, -1));

        jLabel3.setText("Tipo de cliente:");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        buttonGroup1.add(rbNormal);
        rbNormal.setText("Normal");
        jPanel8.add(rbNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        buttonGroup1.add(rbExclusivo);
        rbExclusivo.setText("Exclusivo");
        jPanel8.add(rbExclusivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        btnCrearCliente.setBackground(new java.awt.Color(51, 56, 121));
        btnCrearCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCrearCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCliente.setText("Crear Cliente");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });
        jPanel8.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 150, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, 400, 550));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Tipo"
            }
        ));
        tablaClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaClientes);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, 470, 510));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 18, 506, 550));

        jTabbedPane1.addTab("Clientes", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setAlignmentX(10.0F);
        jPanel10.setAlignmentY(10.0F);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre del producto:");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel10.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, -1));

        jLabel5.setText("Precio:");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        jPanel10.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 160, -1));

        jLabel6.setText("Ubicación:");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));
        jPanel10.add(txtUbicacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 200, -1));

        jLabel7.setText("Stock Inicial:");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));
        jPanel10.add(txtStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 200, -1));

        btnAgregarProducto.setBackground(new java.awt.Color(51, 56, 121));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar Producto");
        jPanel10.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 160, 50));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 910, 149));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Stock", "Ubicación"
            }
        ));
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaProductos);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 870, 370));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 167, 910, 410));

        jTabbedPane1.addTab("Productos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("CLIENTE:");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        cbbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel12.add(cbbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 40));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Productos Disponibles:");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        tablaProductosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Stock:"
            }
        ));
        tablaProductosDisponibles.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaProductosDisponibles);

        jPanel13.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, 300));

        jLabel10.setText("Cantidad:");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));
        jPanel13.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, -1));

        btnAgregarPedido.setText("AGREGAR AL PEDIDO");
        jPanel13.add(btnAgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Pedido Actual:");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 20));

        tablaPedidoActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Subtotal"
            }
        ));
        tablaPedidoActual.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tablaPedidoActual);

        jPanel14.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 320, 300));

        lblTotalPedido.setText("Total: S/  0.00");
        jPanel14.add(lblTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        lblDescuento.setText("Descuento aplicado: NO");
        jPanel14.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        btnConfirmarPedido.setText("CONFIRMAR PEDIDO");
        jPanel14.add(btnConfirmarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedidos", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Resumen del pedido:");
        jLabel12.setAlignmentX(20.0F);
        jLabel12.setAlignmentY(20.0F);
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        txtResumenPedido.setEditable(false);
        txtResumenPedido.setColumns(20);
        txtResumenPedido.setRows(5);
        jScrollPane5.setViewportView(txtResumenPedido);

        jPanel15.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 440, 130));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 940, 152));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Tipo de comprobante:");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        buttonGroup2.add(rbBoleta);
        rbBoleta.setText("Boleta");
        jPanel16.add(rbBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        buttonGroup2.add(rbFactura);
        rbFactura.setText("Factura");
        jPanel16.add(rbFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel14.setText("RUC:");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        jPanel16.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 184, -1));

        btnGenerarComprobante.setText("GENERAR COMPROBANTE");
        jPanel16.add(btnGenerarComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 190, 40));

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 950, 94));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Comprobante Generado");
        jPanel17.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        txtComprobanteGenerado.setEditable(false);
        txtComprobanteGenerado.setColumns(20);
        txtComprobanteGenerado.setRows(5);
        jScrollPane6.setViewportView(txtComprobanteGenerado);

        jPanel17.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 770, 270));

        jPanel4.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, 938, 319));

        jTabbedPane1.addTab("Facturación", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalPedidos.setText("Total de pedido: 0 ");
        jPanel19.add(lblTotalPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lblProductoMasVendido.setText("Producto más pedido: Producto");
        jPanel19.add(lblProductoMasVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        lblTotalNormal.setText("Total vendido (clientes normales): S/ 0.00");
        jPanel19.add(lblTotalNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        lblTotalExclusivo.setText("Total vendido (clientes exclusivos): S/ 0.00");
        jPanel19.add(lblTotalExclusivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jPanel5.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 19, 917, 149));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 228, 917, 339));

        jLabel20.setText("Grafico: (AHI DECIA OPCIONAL) ");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jTabbedPane1.addTab("Indicadores", jPanel5);

        jPanel6.setBackground(new java.awt.Color(237, 236, 236));

        jPanel18.setBackground(new java.awt.Color(237, 236, 236));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAlertaActual.setForeground(new java.awt.Color(0, 0, 0));
        lblAlertaActual.setText("Stock bajo para: (Esto varia segun el producto mas bajo del stock)");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exclamacion-de-diamante.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlertaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(lblAlertaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel18.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 490, 70));

        jPanel21.setBackground(new java.awt.Color(237, 236, 236));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Historial de alertas");
        jPanel21.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 120, 30));

        txtHistorialAlertas.setEditable(false);
        txtHistorialAlertas.setBackground(new java.awt.Color(255, 255, 255));
        txtHistorialAlertas.setColumns(20);
        txtHistorialAlertas.setRows(5);
        jScrollPane7.setViewportView(txtHistorialAlertas);

        jPanel21.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 710, 290));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alerta.png"))); // NOI18N
        jPanel21.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
        jLabel21.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Alertas", jPanel6);

        jPanel7.setBackground(new java.awt.Color(237, 236, 236));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Método de pago:");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 46, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/billete-de-banco (2).png"))); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 30, 40));

        rbEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbEfectivo);
        rbEfectivo.setText("efectivo");
        rbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEfectivoActionPerformed(evt);
            }
        });
        jPanel7.add(rbEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 70, -1));

        rbTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbTarjeta);
        rbTarjeta.setText("Tarjeta");
        jPanel7.add(rbTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        rbYape.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbYape);
        rbYape.setText("Yape");
        jPanel7.add(rbYape, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        lblResultadoPago.setText("Resultado de pago: Esto cambia de acuerdo al tipo de pago ");
        jPanel7.add(lblResultadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 116, -1, -1));

        jLabel18.setText("RECIBO GENERADO");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        txtReciboPago.setEditable(false);
        txtReciboPago.setColumns(20);
        txtReciboPago.setRows(5);
        jScrollPane8.setViewportView(txtReciboPago);

        jPanel7.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 230, 674, 335));

        btnRealizarPago.setBackground(new java.awt.Color(51, 56, 121));
        btnRealizarPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRealizarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarPago.setText("Realizar Pago");
        btnRealizarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRealizarPago.setOpaque(true);
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });
        jPanel7.add(btnRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 130, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-bancaria.png"))); // NOI18N
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 30, 30, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yape-removebg-preview (3).png"))); // NOI18N
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 80));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        lblCodigoTarjeta.setText("Código tarjeta:");

        txtCodigoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCodigoTarjeta)
                .addGap(96, 96, 96)
                .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoTarjeta)
                    .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 550, 50));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 880, 410));

        jTabbedPane1.addTab("Pagos", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI());
        jTabbedPane1.setBackground(new java.awt.Color(34, 86, 136));
        jTabbedPane1.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_formWindowOpened

    private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagoActionPerformed

    }//GEN-LAST:event_btnRealizarPagoActionPerformed

    private void rbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEfectivoActionPerformed

    private void txtCodigoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTarjetaActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String correo = txtCorreo.getText();
        String tipo = rbExclusivo.isSelected() ? "Exclusivo" : "Normal";

        if (nombre.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa los campos.");
            return;
        }

        Cliente cliente;
        if (tipo.equals("Exclusivo")) {
            cliente = new ClienteExclusivo(nombre, correo);
        } else {
            cliente = new ClienteNormal(nombre, correo);
        }

        DefaultTableModel model = (DefaultTableModel) tablaClientes.getModel();
        model.addRow(new Object[]{nombre, correo, tipo});
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Forzar un Look & Feel básico para evitar bordes blancos */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            FormVista vista = new FormVista();

            // Cambiar colores de la barra y pestañas
            vista.jTabbedPane1.setUI(new MetalTabbedPaneUI());
            vista.jTabbedPane1.setBackground(new Color(34, 86, 136));
            vista.jTabbedPane1.setForeground(Color.WHITE);
            vista.jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

            vista.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnGenerarComprobante;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1<thinking>
GestorPedidos.java manages a list of Pedido objects and provides methods to create a new Pedido and get the list of all pedidos.

I can use GestorPedidos.getPedidos() to get all orders and calculate the indicators.

I will implement a method in FormVista.java to calculate and update the indicators:
- Total number of orders (pedidos.size())
- Most ordered product (by summing quantities across all pedidos)
- Total sales for normal clients (sum totals of pedidos with ClienteNormal)
- Total sales for exclusive clients (sum totals of pedidos with ClienteExclusivo)

I will proceed to implement this method in FormVista.java.
</thinking>

<edit_file>
<path>src/Vista/FormVista.java</path>
<content>
<<<<<<< SEARCH
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnGenerarComprobante;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAlertaActual;
    private javax.swing.JLabel lblCodigoTarjeta;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblProductoMasVendido;
    private javax.swing.JLabel lblResultadoPago;
    private javax.swing.JLabel lblTotalExclusivo;
    private javax.swing.JLabel lblTotalNormal;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JLabel lblTotalPedidos;
    private javax.swing.JRadioButton rbBoleta;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JRadioButton rbExclusivo;
    private javax.swing.JRadioButton rbFactura;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JRadioButton rbTarjeta;
    private javax.swing.JRadioButton rbYape;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaPedidoActual;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaProductosDisponibles;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCodigoTarjeta;
    private javax.swing.JTextArea txtComprobanteGenerado;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtHistorialAlertas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextArea txtReciboPago;
    private javax.swing.JTextArea txtResumenPedido;
    private javax.swing.JTextField txtStockProducto;
    private javax.swing.JTextField txtUbicacionProducto;
    // End of variables declaration//GEN-END:variables
=======
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnGenerarComprobante;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAlertaActual;
    private javax.swing.JLabel lblCodigoTarjeta;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblProductoMasVendido;
    private javax.swing.JLabel lblResultadoPago;
    private javax.swing.JLabel lblTotalExclusivo;
    private javax.swing.JLabel lblTotalNormal;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JLabel lblTotalPedidos;
    private javax.swing.JRadioButton rbBoleta;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JRadioButton rbExclusivo;
    private javax.swing.JRadioButton rbFactura;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JRadioButton rbTarjeta;
    private javax.swing.JRadioButton rbYape;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaPedidoActual;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaProductosDisponibles;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCodigoTarjeta;
    private javax.swing.JTextArea txtComprobanteGenerado;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtHistorialAlertas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextArea txtReciboPago;
    private javax.swing.JTextArea txtResumenPedido;
    private javax.swing.JTextField txtStockProducto;
    private javax.swing.JTextField txtUbicacionProducto;
    // End of variables declaration//GEN-END:variables
+
+    private void actualizarIndicadores() {
+        int totalPedidos = gestorPedidos.getPedidos().size();
+        lblTotalPedidos.setText("Total de pedidos: " + totalPedidos);
+
+        Map<String, Integer> productoCantidadMap = new HashMap<>();
+        double totalNormal = 0.0;
+        double totalExclusivo = 0.0;
+
+        for (Pedido pedido : gestorPedidos.getPedidos()) {
+            for (LineaPedido linea : pedido.getLineas()) {
+                String nombreProducto = linea.getProducto().getNombre();
+                int cantidad = linea.getCantidad();
+                productoCantidadMap.put(nombreProducto, productoCantidadMap.getOrDefault(nombreProducto, 0) + cantidad);
+            }
+            if (pedido.getCliente() instanceof Modelo_Cliente.ClienteNormal) {
+                totalNormal += pedido.calcularTotal();
+            } else if (pedido.getCliente() instanceof Modelo_Cliente.ClienteExclusivo) {
+                totalExclusivo += pedido.calcularTotal();
+            }
+        }
+
+        lblTotalNormal.setText(String.format("Total vendido (clientes normales): S/ %.2f", totalNormal));
+        lblTotalExclusivo.setText(String.format("Total vendido (clientes exclusivos): S/ %.2f", totalExclusivo));
+
+        String productoMasVendido = productoCantidadMap.entrySet().stream()
+                .max(Map.Entry.comparingByValue())
+                .map(Map.Entry::getKey)
+                .orElse("Ninguno");
+        lblProductoMasVendido.setText("Producto más pedido: " + productoMasVendido);
+    }
}
